### ISSUE TITLE
[bug] Cannot get it run with Docker

### ISSUE THREAD

**Issue by liemdo** [mikenikles/ghost-v3-google-cloud-storage#3]
Hi Mike,

After I install this package with the docker image ghost:alpine, I get the error `Cannot find module 'ghost-ignition'` when boosting ghost. 

The strange thing is as soon as this package is installed, the ghost-ignition in node_modules/ becomes empty.

**Comment by mikenikles** [comment]
Hi Liem, do you have a sample Github repo where I can reproduce the issue? I'm not familiar with the `ghost:alpine` docker image as I use `node:10-alpine` and don't have that issue (see [code](https://github.com/mikenikles/www-mikenikles-com/blob/master/services/ghost/Dockerfile#L3)).

**Comment by mikenikles** [comment]
@liemdo, following up before I close this ticket.

**Comment by liemdo** [comment]
It works when I use `yarn` instead of `npm` to install packages.

**Comment by markmssd** [comment]
> Hi Liem, do you have a sample Github repo where I can reproduce the issue? I'm not familiar with the `ghost:alpine` docker image as I use `node:10-alpine` and don't have that issue (see [code](https://github.com/mikenikles/www-mikenikles-com/blob/master/services/ghost/Dockerfile#L3)).

Hey @mikenikles ,

How did you go around uploading new themes via the dashboard when running in Google Cloud Run?

Seems like this exceptionally doesn’t go through your storage adapter, as themes HAVE to be in content/themes folder?

**Comment by mikenikles** [comment]
Hi Mark,
I use Ghost as a headless CMS and only consume its REST API to generate a static website based on the content stored in Ghost.

The only way I can think of to add a new theme is to add it to the Docker image itself before you push it to a container registry.
